export const C3_COLUMN_CONSTANTS = {
  main: {
    tabNames: {
      needsApproval: 'Needs Approval',
      approved: 'Approved',
      declined: 'Declined',
    },
    orderDetails: { displayName: 'Order Details', columnKey: 'Order Details' },
    resellerDetails: { displayName: 'Reseller Details', columnKey: 'Reseller Details' },
    country: { displayName: 'Country', columnKey: 'Country' },
    currency: { displayName: 'Currency', columnKey: 'Currency' },
    endCustomerCost: { displayName: 'End Customer Cost', columnKey: 'End Customer Cost' },
    resellerCost: { displayName: 'Reseller Cost', columnKey: 'Reseller Cost' },
    totalCredit: { displayName: 'Total Credit', columnKey: 'Total Credit' },
    unbilledUsage: { displayName: 'Unbilled Usage', columnKey: 'Unbilled Usage' },
    availableCredit: { displayName: 'Available Credit', columnKey: 'Available Credit' },
    pending: { displayName: 'Pending', columnKey: 'Pending' },
    pastDue: { displayName: 'Past Due', columnKey: 'Pastdue' },
    arBalance: { displayName: 'ArBalance', columnKey: 'ArBalance' },
    statusInfo: { displayName: '', columnKey: 'statusInfo' },
    actions: { displayName: 'Actions', columnKey: 'Actions' },
    approvedDetails: { displayName: 'Approved Details', columnKey: 'Approved Details' },
    declinedDetails: { displayName: 'Declined Details', columnKey: 'Declined Details' },
  },
  details: {
    vendor: { displayName: 'Vendor', columnKey: 'Vendor' },
    qty: { displayName: 'Qty', columnKey: 'Qty' },
    currency: { displayName: 'Currency', columnKey: 'Currency' },
    value: { displayName: 'Value', columnKey: 'Value' },
    productName: { displayName: 'Product Name', columnKey: 'productName' },
    billingFrequency: { displayName: 'Billing Frequency', columnKey: 'billingFrequency' },
    billingTerm: { displayName: 'Billing Term', columnKey: 'billingTerm' },
    orderType: { displayName: 'Order Type', columnKey: 'orderType' },
  },
} as const;
