import { PPCCardCategory, PPCCardData } from "../../models/ppc-card.model";
import { APP_ROUTE_CONFIG_URL, INSIGHT_DASHBOARD_ROUTE } from "../constants/constants";

export const ppcCardList: PPCCardData[] = [
  {
    headerImgSrc: '/assets/PPC.svg',
    comingSoonText: '',
    contentHeader: 'Cloud Credit Connector',
    contentDesc: 'Ensures visibility into reseller credit limits and billing compliance to minimize credit risk.',
    actionText: 'PROCEED',
    actionImgSrc: '/assets/Arrow.svg',
    isActive: true,
    navigateURL: `/${APP_ROUTE_CONFIG_URL.C3_DASHBOARD}`,
    applicationType: PPCCardCategory.General,
  },
  {
    headerImgSrc: '/assets/EBC.svg',
    comingSoonText: '',
    contentHeader: 'Cloud Billing Connector',
    contentDesc: 'Streamlined billing engine for invoicing, costs, and ERP/cloud sync.',
    actionText: 'PROCEED',
    actionImgSrc: '/assets/Arrow.svg',
    isActive: true,
    navigateURL: `/${APP_ROUTE_CONFIG_URL.CBC_DASHBOARD}`,
    applicationType: PPCCardCategory.General,
  }, 
  {
    headerImgSrc: '/assets/InsightIcon.svg',
    comingSoonText: '',
    contentHeader: 'MS PAC Subscription Data',
    contentDesc: 'Summarized view of Microsoft Subscriptions, Customers and Orders.',
    actionText: 'PROCEED',
    actionImgSrc: '/assets/Arrow.svg',
    isActive: true,
    navigateURL: `/${APP_ROUTE_CONFIG_URL.INSIGHTS}/${INSIGHT_DASHBOARD_ROUTE.MS_PAC_SUBS_URL}`,
    applicationType: PPCCardCategory.Insights,
  },
  {
    headerImgSrc: '/assets/InsightIcon.svg',
    comingSoonText: '',
    contentHeader: 'Microsoft Security',
    contentDesc: 'Key insights on GDAP, Fraud Event, Consumption Spikes, Customer MFA.',
    actionText: 'PROCEED',
    actionImgSrc: '/assets/Arrow.svg',
    isActive: true,
    navigateURL: `/${APP_ROUTE_CONFIG_URL.INSIGHTS}/${INSIGHT_DASHBOARD_ROUTE.MS_SECURITY_URL}`,
    applicationType: PPCCardCategory.Insights,
  },
  {
    headerImgSrc: '/assets/InsightIcon.svg',
    comingSoonText: '',
    contentHeader: 'Billing Reconciliation',
    contentDesc: 'Reviews billing consistency between ION and other integrated systems.',
    actionText: 'PROCEED',
    actionImgSrc: '/assets/Arrow.svg',
    isActive: true,
    navigateURL: `/${APP_ROUTE_CONFIG_URL.INSIGHTS}/${INSIGHT_DASHBOARD_ROUTE.BILLING_RECON_URL}`,
    applicationType: PPCCardCategory.Insights,
  },
  {
    headerImgSrc: '/assets/insights_dropdown_icon_24_24.svg',
    comingSoonText: '',
    contentHeader: 'Revenue Dashboard',
    contentDesc: 'Gain visibility into revenue trends and performance across geographies',
    actionText: 'PROCEED',
    actionImgSrc: '/assets/Arrow.svg',
    isActive: true,
    navigateURL: `/${APP_ROUTE_CONFIG_URL.INSIGHTS}/${INSIGHT_DASHBOARD_ROUTE.REVENUE_DASHBOARD_URL}`,
    applicationType: PPCCardCategory.Insights,
  },
  {
    headerImgSrc: '/assets/exchange_rate_icon_24_24.svg',
    comingSoonText: '',
    contentHeader: 'Exchange Rate Dashboard',
    contentDesc: 'Track and monitor exchange rates to ensure accurate billing and financial reporting across multiple currencies.',
    actionText: 'PROCEED',
    actionImgSrc: '/assets/Arrow.svg',
    isActive: true,
    navigateURL: `/${APP_ROUTE_CONFIG_URL.INSIGHTS}/${INSIGHT_DASHBOARD_ROUTE.EXCHANGE_RATE_URL}`,
    applicationType: PPCCardCategory.Insights,
  },
  {
    headerImgSrc: '/assets/insights_dropdown_icon_24_24.svg',
    comingSoonText: '',
    contentHeader: 'Operation Tools',
    contentDesc: 'Operational scripts and utilities for platform maintenance and support tasks',
    actionImgSrc: '/assets/Arrow.svg',
    actionText: 'PROCEED',
    isActive: true,
    navigateURL: `/${APP_ROUTE_CONFIG_URL.CLOUD_TOOLS}`,
    applicationType: PPCCardCategory.CloudTools,
  },
  {
    headerImgSrc: '/assets/InsightIcon.svg',
    comingSoonText: '',
    contentHeader: 'S-ION Regional Overview',
    contentDesc: 'Regional overview of key business metrics.',
    actionImgSrc: '/assets/Arrow.svg',
    actionText: 'PROCEED',
    isActive: true,
    navigateURL: `/${APP_ROUTE_CONFIG_URL.INSIGHTS}/${INSIGHT_DASHBOARD_ROUTE.ION_REGIONAL_OVERVIEW}`,
    applicationType: PPCCardCategory.Insights,
  },
  {
    headerImgSrc: '/assets/insights_dropdown_icon_24_24.svg',
    comingSoonText: '',
    contentHeader: 'Revenue Dashboard V2',
    contentDesc: 'Gain visibility into revenue trends and performance across geographies',
    actionText: 'PROCEED',
    actionImgSrc: '/assets/Arrow.svg',
    isActive: true,
    navigateURL: `/${APP_ROUTE_CONFIG_URL.INSIGHTS}/${INSIGHT_DASHBOARD_ROUTE.REVENUE_DASHBOARD_PHASE2_URL}`,
    applicationType: PPCCardCategory.Insights,
  },
  {
    headerImgSrc: '/assets/InsightIcon.svg',
    comingSoonText: '',
    contentHeader: 'S-ION Order Data',
    contentDesc: 'Centralized view of SION Orders data for analytics and reporting',
    actionImgSrc: '/assets/Arrow.svg',
    actionText: 'PROCEED',
    isActive: true,
    navigateURL: `/${APP_ROUTE_CONFIG_URL.INSIGHTS}/${INSIGHT_DASHBOARD_ROUTE.ION_ORDER_DATA_URL}`,
    applicationType: PPCCardCategory.Insights,
  },
  {
    headerImgSrc: '/assets/InsightIcon.svg',
    comingSoonText: '',
    contentHeader: 'End Customer Churn',
    contentDesc: 'Analyze End Customer Churn and retention patterns',
    actionText: 'PROCEED',
    actionImgSrc: '/assets/Arrow.svg',
    isActive: true,
    navigateURL: `/${APP_ROUTE_CONFIG_URL.INSIGHTS}/${INSIGHT_DASHBOARD_ROUTE.END_CUSTOMER_CHURN_URL}`,
    applicationType: PPCCardCategory.Insights,
  },
];
